[project]
name = "passiogo-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.2.8",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "passiogo>=0.2.2",
    "rapidfuzz>=3.13.0",
]
